# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdminlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminlogin(self):
    self.driver.get("http://localhost/SE%20Hotel%20Management%20Part/index.php")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".btns:nth-child(2)").click()
    self.driver.find_element(By.NAME, "Emp_Email").click()
    self.driver.find_element(By.NAME, "Emp_Email").send_keys("admin@gmail.com")
    self.driver.find_element(By.NAME, "Emp_Password").click()
    self.driver.find_element(By.NAME, "Emp_Password").send_keys("1234")
    self.driver.find_element(By.NAME, "Emp_login_submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pagebtn:nth-child(2)").click()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .btn-success").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".pagebtn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pagebtn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pagebtn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
