# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signin(self):
    self.driver.get("http://localhost/SE%20Hotel%20Management%20Part/index.php/SE%20Hotel%20Management%20Part/index.php")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.NAME, "Username").click()
    self.driver.find_element(By.NAME, "Username").send_keys("Vibhansh")
    self.driver.find_element(By.NAME, "Email").click()
    self.driver.find_element(By.NAME, "Email").send_keys("vibhansh@gmail.com")
    self.driver.find_element(By.NAME, "Password").click()
    self.driver.find_element(By.NAME, "Password").send_keys("Vibhansh")
    self.driver.find_element(By.NAME, "user_login_submit").click()
  
